name: Test Docker Build

on:
  push:
    branches:
      - "master"
    tags:
      - "*"

jobs:

  bockerize_build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: robsontenorio/test-buildx
        flavor: latest=false
        tags: |
          type=ref,event=tag
          type=raw,enable=${{ github.ref == 'refs/heads/master' }},value=latest
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          
    - name: COPY CONTAINER IMAGE NAME
      run: echo "CONTAINER IMAGE:" ${{ github.ref_name }}-${{ github.sha }}
